apiVersion: v1
kind: Service
metadata:
  name: springboot-service-blue
  namespace: virtual-production
spec:
  selector:
    app: springboot-app-blue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080