apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: virtual-front-certificate
  namespace: virtual-development
spec:
  secretName: virtual-ingress-cert
  dnsNames:
    - development.65.co.ucll.cloud
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer