apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: virtual-back-certificate
  namespace: virtual-qa
spec:
  secretName: api-ingress-cert
  dnsNames:
    - api.qa.65.co.ucll.cloud
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer