apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: virtual-production
  name: nextjs-app
spec:
  replicas: 1
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 10}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
        - name: nextjs
          image: mr1dentity/frontend-image:green
          ports:
            - containerPort: 3000