name: backend Pipeline

on:
  push:
    branches:
      - master
      - dev
      - qa
      - "*"

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "17"

      - name: Run Backend Tests
        run: |
          cd backend
          mvn test  # Assuming you are using Maven for Java backend tests

  determine-color:
    if: github.ref == 'refs/heads/master'
    needs: run-tests
    runs-on: ubuntu-latest
    outputs:
      step_output: ${{ steps.set_color.outputs.color }}

    steps:
      - name: Determine Deployment Color
        id: set_color
        run: echo "::set-output name=color::$(bash determine_color.sh)"

  deploy-master:
    runs-on: ubuntu-latest
    needs:
      - run-tests
      - determine-color
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Docker Image
        run: |
          COLOR=${{ needs.determine-color.outputs.step_output }}
          docker build -t mr1dentity/backend-image:$COLOR backend/

      - name: Push Backend Docker Image
        run: docker push mr1dentity/backend-image:$COLOR

  deploy-dev:
    runs-on: ubuntu-latest
    needs:
      - run-tests
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Docker Image
        run: docker build -t mr1dentity/backend-image:dev backend/

      - name: Push Backend Docker Image
        run: docker push mr1dentity/backend-image:dev

  deploy-qa:
    runs-on: ubuntu-latest
    needs:
      - run-tests
    if: github.ref == 'refs/heads/qa'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Docker Image
        run: docker build -t mr1dentity/backend-image:qa backend/

      - name: Push Backend Docker Image
        run: docker push mr1dentity/backend-image:qa
