name: frontend Pipeline

on:
  push:
    branches:
      - master
      - dev
      - qa
      - "*"

jobs:
  determine-color:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    outputs:
      step_output: ${{ steps.set_color.outputs.color }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: ls
        uses: ls -l
      - name: Determine Deployment Color
        id: set_color
        run: sh determine_color.sh
        shell: pwsh

  deploy-master:
    runs-on: ubuntu-latest
    needs: determine-color
    if: github.ref == 'refs/heads/master'
    env:
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: yVGeMAiKykDq8dtfuIe49IRXvZInmZE4DqR+MsQvYXc=
      NEXT_PUBLIC_URL: http://springboot-service.virtual-production:8080
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create .env file
        run: echo "NEXTAUTH_URL=${NEXTAUTH_URL}" >> frontend/.env && echo "NEXTAUTH_SECRET=${NEXTAUTH_SECRET}" >> frontend/.env && echo "NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}" >> frontend/.env

      - name: Build Frontend Docker Image
        run: |
          COLOR=${{ needs.determine-color.outputs.step_output }}
          docker build -t mr1dentity/frontend-image:$COLOR frontend/

      - name: Push Frontend Docker Image
        run: docker push mr1dentity/frontend-image:$COLOR

  deploy-dev:
    runs-on: ubuntu-latest
    # needs:
    #   - run-tests
    if: github.ref == 'refs/heads/dev'
    env:
      NEXTAUTH_URL: http://frontend-service.virtual-production
      NEXTAUTH_SECRET: yVGeMAiKykDq8dtfuIe49IRXvZInmZE4DqR+MsQvYXc=
      NEXT_PUBLIC_URL: https://api.virtual.65.co.ucll.cloud
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create .env file
        run: echo "NEXTAUTH_URL=${NEXTAUTH_URL}" >> frontend/.env && echo "NEXTAUTH_SECRET=${NEXTAUTH_SECRET}" >> frontend/.env && echo "NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}" >> frontend/.env

      - name: Build Frontend Docker Image
        run: docker build -t mr1dentity/frontend-image:dev frontend/

      - name: Push Frontend Docker Image
        run: docker push mr1dentity/frontend-image:dev

  deploy-qa:
    runs-on: ubuntu-latest
    # needs:
    #   - run-tests
    if: github.ref == 'refs/heads/qa'
    env:
      NEXTAUTH_URL: http://frontend-service.virtual-production
      NEXTAUTH_SECRET: yVGeMAiKykDq8dtfuIe49IRXvZInmZE4DqR+MsQvYXc=
      NEXT_PUBLIC_URL: http://springboot-service.virtual-production:8080
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create .env file
        run: echo "NEXTAUTH_URL=${NEXTAUTH_URL}" >> frontend/.env && echo "NEXTAUTH_SECRET=${NEXTAUTH_SECRET}" >> frontend/.env && echo "NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}" >> frontend/.env

      - name: Build Frontend Docker Image
        run: docker build -t mr1dentity/frontend-image:qa frontend/

      - name: Push Frontend Docker Image
        run: docker push mr1dentity/frontend-image:qa
